sync with helm template

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -49,6 +49,9 @@ stages:
       bx cr quota
       echo "If needed, discard older images using: bx cr image-rm"
 
+      echo "Current content of image registry"
+      bx cr images
+
       echo "Checking registry namespace: ${REGISTRY_NAMESPACE}"
       NS=$( bx cr namespaces | grep ${REGISTRY_NAMESPACE} ||: )
       if [ -z "${NS}" ]; then
@@ -58,32 +61,32 @@ stages:
       else 
           echo "Registry namespace ${REGISTRY_NAMESPACE} found."
       fi
+      echo "=========================================================="
+      TIMESTAMP=$( date -u "+%Y%m%d%H%M%SUTC")
+      IMAGE_TAG=${BUILD_NUMBER}-${TIMESTAMP}
+      if [ ! -z ${GIT_COMMIT} ]; then
+        GIT_COMMIT_SHORT=$( echo ${GIT_COMMIT} | head -c 8 ) 
+        IMAGE_TAG=${IMAGE_TAG}-${GIT_COMMIT_SHORT}; 
+      fi
+      echo -e "Building container image: ${IMAGE_NAME}:${IMAGE_TAG}"
+      set -x
+      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} .
+      set +x
+      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
 
-      echo -e "Existing images in registry"
-      bx cr images
+      # Set PIPELINE_IMAGE_URL for subsequent jobs in stage (e.g. Vulnerability Advisor)
+      export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER"
+
+      bx cr images --restrict ${REGISTRY_NAMESPACE}/${IMAGE_NAME}
 
       echo "=========================================================="
-      echo -e "Building container image: ${IMAGE_NAME}:${BUILD_NUMBER}"
-      set -x
-      bx cr build -t ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER} .
-      set +x
-      bx cr image-inspect ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER}
-
-      # When 'bx' commands are in the pipeline job config directly, the image URL will automatically be passed 
-      # along with the build result as env variable PIPELINE_IMAGE_URL to any subsequent job consuming this build result. 
-      # When the job is sourc'ing an external shell script, or to pass a different image URL than the one inferred by the pipeline,
-      # please uncomment and modify the environment variable the following line.
-      # export PIPELINE_IMAGE_URL="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER"
-
-      ######################################################################################
-      # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE    #
-      ######################################################################################
+      echo "COPYING ARTIFACTS needed for deployment and testing (in particular build.properties)"
       echo -e "Checking archive dir presence"
       mkdir -p $ARCHIVE_DIR
 
       # pass image information along via build.properties for Vulnerability Advisor scan
       echo "IMAGE_NAME=${IMAGE_NAME}" >> $ARCHIVE_DIR/build.properties
-      echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
+      echo "IMAGE_TAG=${IMAGE_TAG}" >> $ARCHIVE_DIR/build.properties
       echo "REGISTRY_URL=${REGISTRY_URL}" >> $ARCHIVE_DIR/build.properties
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $ARCHIVE_DIR/build.properties
       echo "File 'build.properties' created for passing env variables to subsequent pipeline jobs:"
@@ -92,7 +95,7 @@ stages:
       #Update deployment.yml with image name
       if [ -f deployment.yml ]; then
           echo "UPDATING DEPLOYMENT MANIFEST:"
-          sed -i "s~^\([[:blank:]]*\)image:.*$~\1image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_NUMBER}~" deployment.yml
+          sed -i "s~^\([[:blank:]]*\)image:.*$~\1image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}~" deployment.yml
           cat deployment.yml
           if [ ! -f $ARCHIVE_DIR/deployment.yml ]; then # no need to copy if working in ./ already    
               cp deployment.yml $ARCHIVE_DIR/
@@ -132,25 +135,26 @@ stages:
       # ------------------
       # source: https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/check_vulnerabilities.sh
       # Input env variables (can be received via a pipeline environment properties.file.
-      echo "IMAGE_NAME=${IMAGE_NAME}"
-      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "PIPELINE_IMAGE_URL=${PIPELINE_IMAGE_URL}"
       echo "REGISTRY_URL=${REGISTRY_URL}"
       echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "IMAGE_TAG=${IMAGE_TAG}"
       #View build properties
       # cat build.properties
       # also run 'env' command to find all available env variables
       # or learn more about the available environment variables at:
       # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
 
-      bx cr images
-      PIPELINE_IMAGE_URL=$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$BUILD_NUMBER
+      bx cr images --restrict ${REGISTRY_NAMESPACE}/${IMAGE_NAME}
+      PIPELINE_IMAGE_URL=${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
       echo -e "Checking vulnerabilities in image: ${PIPELINE_IMAGE_URL}"
       for ITER in {1..30}
       do
         set +e
-        STATUS=$( bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq '.[0].status' )
+        STATUS=$( bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq -r '.[0].status' )
         set -e
-        if [[ ${STATUS} == *OK* ]]; then
+        if [[ ${STATUS} == "OK" || ${STATUS} == "FAIL" ]]; then
           break
         fi
         echo -e "${ITER} STATUS ${STATUS} : A vulnerability report was not found for the specified image."
@@ -159,16 +163,16 @@ stages:
         sleep 10
       done
       set +e
-      bx cr va ${PIPELINE_IMAGE_URL}
+      bx cr va -e ${PIPELINE_IMAGE_URL}
       set -e
-      [[ $(bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq '.[0].status') == *OK* ]] || { echo "ERROR: The vulnerability scan was not successful, check the OUTPUT of the command and try again."; exit 1; }
+      [[ $(bx cr va -e -o json ${PIPELINE_IMAGE_URL} | jq -r '.[0].status') == "OK" ]] || { echo "ERROR: The vulnerability scan was not successful, check the OUTPUT of the command and try again."; exit 1; }
 - name: DEPLOY
   inputs:
   - type: job
     stage: BUILD
     job: Container build
   jobs:
-  - name: Deploy Kubernetes Pod
+  - name: Deploy Kubernetes
     type: deployer
     target:
       region_id: ${PROD_REGION_ID}
@@ -206,8 +210,6 @@ stages:
         echo "$PIPELINE_KUBERNETES_CLUSTER_NAME not created or workers not ready"
         exit 1
       fi
-      #Connect to a different container-service api by uncommenting and specifying an api endpoint
-      #bx cs init --host https://us-south.containers.bluemix.net
       echo ""
       echo "DEPLOYING USING MANIFEST:"
       cat deployment.yml
