reformat deploy job command

diff --git a/.bluemix/pipeline2.yml b/.bluemix/pipeline2.yml
--- a/.bluemix/pipeline2.yml
+++ b/.bluemix/pipeline2.yml
@@ -95,53 +95,67 @@ stages:
     PORT: '80'
     CONTAINER_NAME: ${CF_APP}
     DEPLOY_TYPE: red_black
-    COMMAND: "#!/bin/bash\n# The following are some example deployment scripts.  Use\
-      \ these as is or fork them and include your updates here:\necho -e \"${label_color}Starting\
-      \ deployment script${no_color}\"\n\n\n# To view/fork this script goto: https://github.com/Osthanes/deployscripts\n\
-      # git_retry will retry git calls to prevent pipeline failure on temporary github\
-      \ problems\n# the code can be found in git_util.sh at https://github.com/Osthanes/container_deployer\n\
-      git_retry clone https://github.com/Osthanes/deployscripts.git deployscripts\n\
-      \n\n# You can deploy your Image as either a single Container or as a Container\
-      \ \n# Group.  A Container Group deploys a number of containers to enhance\n\
-      # scalability or reliability.  By default we will deploy as a single \n# container.\
-      \  To switch to a group deploy, comment out the line below\n# containing deploycontainer.sh\
-      \ and uncomment the line for deploygroup.sh\n\n# Deploy with containers:\n#\
-      \ Optional environment properties (can be set directly in this script, or defined\
-      \ as environment properties):\n#      NAME              Value         Description\n\
-      #   =============      =========     ==============\n#   BIND_TO           \
-      \  String       Specify a Bluemix application name that whose bound services\
-      \ you wish to make available to the container.  By default this is not set.\n\
-      #   CONTAINER_SIZE      String       Specify container size: m1.tiny (256),\
-      \ m1.small (512), m1.medium (1024), m1.large (2048).\n#                    \
-      \                Default is m1.tiny (256).\n#   CONCURRENT_VERSIONS Number \
-      \      Number of versions of this container to leave active.  \n#          \
-      \                          Default is 1\n#\n#/bin/bash deployscripts/deploycontainer.sh\n\
-      \n# Deploy Container Group:\n# Optional environment properties (can be set directly\
-      \ in this script, or defined as environment properties):\n#      NAME      \
-      \        Value         Description\n#   =============      =========     ==============\n\
-      #   ROUTE_HOSTNAME      String       Specify the Hostname for the Cloud Foundry\
-      \ Route you wish to assign to this container group.  By default this is not\
-      \ set.\n#   ROUTE_DOMAIN        String       Specify domain name for the Cloud\
-      \ Foundry Route you wish to assign to this container group.  By default this\
-      \ is not set.\n#   BIND_TO             String       Specify a Bluemix application\
-      \ name that whose bound services you wish to make available to the container.\
-      \  By default this is not set.\n#   DESIRED_INSTANCES:  Number       Specify\
-      \ the number of instances in the group.  Default value is 1.\n#   AUTO_RECOVERY:\
-      \      Boolean      Set auto-recovery to true/false.  Default value is false.\n\
-      \n#                                    Default is false.\n#   CONTAINER_SIZE\
-      \      String       Specify container size: m1.tiny (256), m1.small (512), m1.medium\
-      \ (1024), m1.large (2048).\n#                                    Default is\
-      \ m1.tiny (256).\n#   CONCURRENT_VERSIONS Number       Number of versions of\
-      \ this group to leave active.\n#                                    Default\
-      \ is 1\n# IF YOU WANT CONTAINER GROUPS .. uncomment the next line, and comment\
-      \ out the previous deployment line (/bin/bash deployscripts/deploygroup.sh)\n\
-      /bin/bash deployscripts/deploygroup.sh\n\nRESULT=$?\n\n#########################\n\
-      # Environment DETAILS   #\n#########################\n# The environment has\
-      \ been setup.\n# The Cloud Foundry CLI (cf), IBM Container Service CLI (ice),\
-      \ Git client (git), IDS Inventory CLI (ids-inv) and Python 2.7.3 (python) have\
-      \ been installed.\n# Based on the organization and space selected in the Job\
-      \ credentials are in place for both IBM Container Service and IBM Bluemix\n\n\
-      # The following colors have been defined to help with presentation of logs:\
-      \ green, red, label_color, no_color.\nif [ $RESULT -ne 0 ]; then\n    echo -e\
-      \ \"${red}Executed failed or had warnings ${no_color}\"\n    ${EXT_DIR}/print_help.sh\n\
-      \    exit $RESULT\nfi\necho -e \"${green}Execution complete${no_label}\""
+    COMMAND: |
+      #!/bin/bash
+      # The following are some example deployment scripts.  Use these as is or fork them and include your updates here:
+      echo -e "${label_color}Starting deployment script${no_color}"
+      
+      
+      # To view/fork this script goto: https://github.com/Osthanes/deployscripts
+      # git_retry will retry git calls to prevent pipeline failure on temporary github problems
+      # the code can be found in git_util.sh at https://github.com/Osthanes/container_deployer
+      git_retry clone https://github.com/Osthanes/deployscripts.git deployscripts
+      
+      
+      # You can deploy your Image as either a single Container or as a Container 
+      # Group.  A Container Group deploys a number of containers to enhance
+      # scalability or reliability.  By default we will deploy as a single 
+      # container.  To switch to a group deploy, comment out the line below
+      # containing deploycontainer.sh and uncomment the line for deploygroup.sh
+      
+      # Deploy with containers:
+      # Optional environment properties (can be set directly in this script, or defined as environment properties):
+      #      NAME              Value         Description
+      #   =============      =========     ==============
+      #   BIND_TO             String       Specify a Bluemix application name that whose bound services you wish to make available to the container.  By default this is not set.
+      #   CONTAINER_SIZE      String       Specify container size: m1.tiny (256), m1.small (512), m1.medium (1024), m1.large (2048).
+      #                                    Default is m1.tiny (256).
+      #   CONCURRENT_VERSIONS Number       Number of versions of this container to leave active.  
+      #                                    Default is 1
+      #
+      #/bin/bash deployscripts/deploycontainer.sh
+      
+      # Deploy Container Group:
+      # Optional environment properties (can be set directly in this script, or defined as environment properties):
+      #      NAME              Value         Description
+      #   =============      =========     ==============
+      #   ROUTE_HOSTNAME      String       Specify the Hostname for the Cloud Foundry Route you wish to assign to this container group.  By default this is not set.
+      #   ROUTE_DOMAIN        String       Specify domain name for the Cloud Foundry Route you wish to assign to this container group.  By default this is not set.
+      #   BIND_TO             String       Specify a Bluemix application name that whose bound services you wish to make available to the container.  By default this is not set.
+      #   DESIRED_INSTANCES:  Number       Specify the number of instances in the group.  Default value is 1.
+      #   AUTO_RECOVERY:      Boolean      Set auto-recovery to true/false.  Default value is false.
+      
+      #                                    Default is false.
+      #   CONTAINER_SIZE      String       Specify container size: m1.tiny (256), m1.small (512), m1.medium (1024), m1.large (2048).
+      #                                    Default is m1.tiny (256).
+      #   CONCURRENT_VERSIONS Number       Number of versions of this group to leave active.
+      #                                    Default is 1
+      # IF YOU WANT CONTAINER GROUPS .. uncomment the next line, and comment out the previous deployment line (/bin/bash deployscripts/deploygroup.sh)
+      /bin/bash deployscripts/deploygroup.sh
+      
+      RESULT=$?
+      
+      #########################
+      # Environment DETAILS   #
+      #########################
+      # The environment has been setup.
+      # The Cloud Foundry CLI (cf), IBM Container Service CLI (ice), Git client (git), IDS Inventory CLI (ids-inv) and Python 2.7.3 (python) have been installed.
+      # Based on the organization and space selected in the Job credentials are in place for both IBM Container Service and IBM Bluemix
+      
+      # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.
+      if [ $RESULT -ne 0 ]; then
+          echo -e "${red}Executed failed or had warnings ${no_color}"
+          ${EXT_DIR}/print_help.sh
+          exit $RESULT
+      fi
+      echo -e "${green}Execution complete${no_label}"
