use new container build job

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -7,78 +7,95 @@ stages:
     service: ${GIT_REPO}    
   triggers:
   - type: commit
+  properties:
+  - name: CHART_NAME
+    value: ${CHART_NAME}
+    type: text  
   jobs:
-  - name: Container build
+  - name: Build image
     type: builder
-    extension_id: ibm.devops.services.pipeline.container.builder
+    build_type: cr
+    artifact_dir: output
     target:
-      region_id: ${PROD_REGION_ID}
-      organization: ${PROD_ORG_NAME}
-      space: ${PROD_SPACE_NAME}
-    IMAGE_NAME: ${CF_APP_NAME}
-    USE_CACHED_LAYERS: 'true'
-    COMMAND: |
+      region_id: ${REGISTRY_REGION_ID}
+      api_key: ${API_KEY}
+    namespace: ${REGISTRY_NAMESPACE}
+    image_name: ${CF_APP_NAME}
+    script: |
       #!/bin/bash
-      # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.  
-      echo -e "${label_color}Starting build script${no_color}"
-      
-      # The IBM Container Service CLI (ice), Git client (git), IDS Inventory CLI (ids-inv) and Python 2.7.3 (python) have been installed.
-      # Based on the organization and space selected in the Job credentials are in place for both IBM Container Service and IBM Bluemix 
-      #####################
-      # Run unit tests    #
-      #####################
-      echo -e "${label_color}No unit tests cases have been checked in ${no_color}"
-      
-      ######################################
-      # Build Container via Dockerfile     #
-      ######################################
-      
-      # REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}
-      # FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:${APPLICATION_VERSION}   
-      
-      # Possible adding retries to build the image
+      #set -x
+
+      echo -e "Build environment variables:"
+      echo "REGISTRY_URL=${REGISTRY_URL}"
+      echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}"
+      echo "IMAGE_NAME=${IMAGE_NAME}"
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
+
+      # Learn more about the available environment variables at:
+      # https://console.bluemix.net/docs/services/ContinuousDelivery/pipeline_deploy_var.html#deliverypipeline_environment
+
+      # To review or change build options use:
+      # bx cr build --help
+
+      echo "=========================================================="
+      echo "Checking for Dockerfile at the repository root"
       if [ -f Dockerfile ]; then 
-          echo -e "${label_color}BUILDING ${FULL_REPOSITORY_NAME} ${no_color}"
-          ${EXT_DIR}/utilities/sendMessage.sh -l info -m "New container build requested for ${FULL_REPOSITORY_NAME}"
-          # build image
-          BUILD_COMMAND=""
-          if [ "${USE_CACHED_LAYERS}" == "true" ]; then 
-              BUILD_COMMAND="build --pull --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}"
-              ice_retry ${BUILD_COMMAND}
-              RESULT=$?
-          else 
-              BUILD_COMMAND="build --no-cache --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}"
-              ice_retry ${BUILD_COMMAND}
-              RESULT=$?
-          fi 
-      
-          if [ $RESULT -ne 0 ]; then
-              echo -e "${red}Error building image ${no_color}" | tee -a "$ERROR_LOG_FILE"
-              echo "Build command: ice ${BUILD_COMMAND}"
-              ice info 
-              ice images
-              ${EXT_DIR}/print_help.sh
-              ${EXT_DIR}/utilities/sendMessage.sh -l bad -m "Container build of ${FULL_REPOSITORY_NAME} failed"
-              exit 1
-          else
-              ${EXT_DIR}/utilities/sendMessage.sh -l good -m "Container build of ${FULL_REPOSITORY_NAME} was successful"
-              echo -e "${green}Container build of ${FULL_REPOSITORY_NAME} was successful ${no_color}"
-          fi  
-      else 
-          echo -e "${red}Dockerfile not found at the repository root${no_color}"
+        echo "Dockerfile found"
+      else
+          echo "Dockerfile not found"
           exit 1
-      fi  
-      
+      fi
+
+      echo "=========================================================="
+      echo "Checking registry current plan and quota"
+      bx cr plan
+      bx cr quota
+      echo "If needed, discard older images using: bx cr image-rm"
+
+      echo "Checking registry namespace: ${REGISTRY_NAMESPACE}"
+      NS=$( bx cr namespaces | grep ${REGISTRY_NAMESPACE} ||: )
+      if [ -z ${NS} ]; then
+          echo "Registry namespace ${REGISTRY_NAMESPACE} not found, creating it."
+          bx cr namespace-add ${REGISTRY_NAMESPACE}
+          echo "Registry namespace ${REGISTRY_NAMESPACE} created."
+      else 
+          echo "Registry namespace ${REGISTRY_NAMESPACE} found."
+      fi
+
+      echo -e "Existing images in registry"
+      bx cr images
+
+      echo "=========================================================="
+      echo -e "Building container image: ${IMAGE_NAME}:${BUILD_NUMBER}"
+      IMAGE_LOCATION=${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}
+      set -x
+      bx cr build -t ${IMAGE_LOCATION}:${BUILD_NUMBER} .
+      set +x
+      bx cr image-inspect ${IMAGE_LOCATION}:${BUILD_NUMBER}
+
       ######################################################################################
       # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE    #
       ######################################################################################
+      echo -e "Checking archive dir presence"
+      mkdir -p $ARCHIVE_DIR
+
+      # Copy scripts (incl. deploy scripts)
+      if [ ! -d $ARCHIVE_DIR/scripts/ ]; then # no need to copy if working in ./ already
+        cp -r ./scripts/ $ARCHIVE_DIR/
+      fi
+
+      # IMAGE_NAME from build.properties is used by Vulnerability Advisor job to reference the image qualified location in registry
       echo "IMAGE_NAME=${FULL_REPOSITORY_NAME}" >> $ARCHIVE_DIR/build.properties
+
+      #Update deployment.yml with image name
       if [ -f deployment.yml ]; then
-          #Update deployment.yml with image name
           echo "UPDATING DEPLOYMENT MANIFEST:"
           sed -i "s~^\([[:blank:]]*\)image:.*$~\1image: ${FULL_REPOSITORY_NAME}~" deployment.yml
           cat deployment.yml
-          cp deployment.yml $ARCHIVE_DIR/
+          if [ ! -f $ARCHIVE_DIR/deployment.yml ]; then # no need to copy if working in ./ already    
+              cp deployment.yml $ARCHIVE_DIR/
+          fi
       else 
           echo -e "${red}Kubernetes deployment file 'deployment.yml' not found at the repository root${no_color}"
           exit 1
@@ -87,7 +104,7 @@ stages:
   inputs:
   - type: job
     stage: BUILD
-    job: Container build
+    job: Build image
   triggers:
   - type: stage
   properties:
@@ -120,29 +137,24 @@ stages:
     script: |
       #!/bin/bash
       #set -x
-
       #Check cluster availability
       ip_addr=$(bx cs workers $PIPELINE_KUBERNETES_CLUSTER_NAME | grep normal | awk '{ print $2 }')
       if [ -z $ip_addr ]; then
         echo "$PIPELINE_KUBERNETES_CLUSTER_NAME not created or workers not ready"
         exit 1
       fi
-
       #Connect to a different container-service api by uncommenting and specifying an api endpoint
       #bx cs init --host https://us-south.containers.bluemix.net
       echo ""
       echo "DEPLOYING USING MANIFEST:"
       cat deployment.yml
       kubectl apply -f deployment.yml  
-
       echo ""
       echo "DEPLOYED SERVICE:"
       kubectl describe services hello-service
-
       echo ""
       echo "DEPLOYED PODS:"
       kubectl describe pods --selector app=hello-app
-
       port=$(kubectl get services | grep hello-service | sed 's/.*:\([0-9]*\).*/\1/g')
       echo ""
       echo "VIEW THE APPLICATION AT: http://$ip_addr:$port"
